package com.kgl.vma.enums

import com.kgl.vma.utils.*
import org.lwjgl.util.vma.*

actual enum class AllocationCreate(override val value: Int) : VmaFlag<AllocationCreate> {
	DEDICATED_MEMORY(Vma.VMA_ALLOCATION_CREATE_DEDICATED_MEMORY_BIT),
	NEVER_ALLOCATE(Vma.VMA_ALLOCATION_CREATE_NEVER_ALLOCATE_BIT),
	MAPPED(Vma.VMA_ALLOCATION_CREATE_MAPPED_BIT),
	CAN_BECOME_LOST(Vma.VMA_ALLOCATION_CREATE_CAN_BECOME_LOST_BIT),
	CAN_MAKE_OTHER_LOST(Vma.VMA_ALLOCATION_CREATE_CAN_MAKE_OTHER_LOST_BIT),
	USER_DATA_COPY_STRING(Vma.VMA_ALLOCATION_CREATE_USER_DATA_COPY_STRING_BIT),
	UPPER_ADDRESS(Vma.VMA_ALLOCATION_CREATE_UPPER_ADDRESS_BIT),
	DONT_BIND(Vma.VMA_ALLOCATION_CREATE_DONT_BIND_BIT),
	STRATEGY_BEST_FIT(Vma.VMA_ALLOCATION_CREATE_STRATEGY_BEST_FIT_BIT),
	STRATEGY_WORST_FIT(Vma.VMA_ALLOCATION_CREATE_STRATEGY_WORST_FIT_BIT),
	STRATEGY_FIRST_FIT(Vma.VMA_ALLOCATION_CREATE_STRATEGY_FIRST_FIT_BIT),
	STRATEGY_MIN_MEMORY(Vma.VMA_ALLOCATION_CREATE_STRATEGY_MIN_MEMORY_BIT),
	STRATEGY_MIN_TIME(Vma.VMA_ALLOCATION_CREATE_STRATEGY_MIN_TIME_BIT),
	STRATEGY_MIN_FRAGMENTATION(Vma.VMA_ALLOCATION_CREATE_STRATEGY_MIN_FRAGMENTATION_BIT);
	
	actual companion object {
		private val enumLookUpMap: Map<Int, AllocationCreate> =
			enumValues<AllocationCreate>().associateBy { it.value }
		
		fun fromMultiple(value: Int): VmaFlag<AllocationCreate>? = if (value == 0) null else VmaFlag(value)
		
		fun from(value: Int): AllocationCreate = enumLookUpMap[value]!!
	}
}

actual val AllocationCreate.Companion.STRATEGY_MASK: VmaFlag<AllocationCreate>
	get() = VmaFlag(Vma.VMA_ALLOCATION_CREATE_STRATEGY_MASK)
